version: 2.1

workflows:
  versions: 2.1
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/
    docker: 
      - image: circleci/node:4.8.2 # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
        name: install-npm-package
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
      - test:
        name: package-test
        command: npm test